brush up `channel-upgrade execute` subcommand
Signed-off-by: Masanori Yoshida <masanori.yoshida@datachain.jp>

diff --git a/tests/cases/tm2tm/scripts/test-channel-upgrade b/tests/cases/tm2tm/scripts/test-channel-upgrade
--- a/tests/cases/tm2tm/scripts/test-channel-upgrade
+++ b/tests/cases/tm2tm/scripts/test-channel-upgrade
@@ -32,31 +32,39 @@ dstAltConnectionId=$($RLY paths list --json | jq --raw-output --arg path_name "$
 # resume the original config.json
 mv $origconfig "$RELAYER_CONF/config/config.json"
 
+checkResult() {
+    expectedSrcConnectionId=$1
+    expectedDstConnectionId=$2
+    pathSrcConnectionId=$($RLY paths list --json | jq --raw-output --arg path_name "$PATH_NAME" '.[$path_name].src."connection-id"')
+    pathDstConnectionId=$($RLY paths list --json | jq --raw-output --arg path_name "$PATH_NAME" '.[$path_name].dst."connection-id"')
+    if [ "$pathSrcConnectionId" != "$expectedSrcConnectionId" ]
+    then
+	echo 'src path config update failed'
+	exit 1
+    elif [ "$pathDstConnectionId" != "$expectedDstConnectionId" ]
+    then
+	echo 'dst path config update failed'
+	exit 1
+    fi
+}
+
 # test channel upgrade (crossing-hello)
-$RLY tx channel-upgrade init ibc01 ibc0 --ordering ORDER_UNORDERED --connection-hops $srcAltConnectionId --version ics20-1
-$RLY tx channel-upgrade init ibc01 ibc1 --ordering ORDER_UNORDERED --connection-hops $dstAltConnectionId --version ics20-1
+$RLY tx channel-upgrade init ibc01 ibc0 --ordering unordered --connection-hops $srcAltConnectionId --version ics20-1
+$RLY tx channel-upgrade init ibc01 ibc1 --ordering UnOrdered --connection-hops $dstAltConnectionId --version ics20-1
 $RLY tx channel-upgrade execute ibc01
-pathSrcConnectionId=$($RLY paths list --json | jq --raw-output --arg path_name "$PATH_NAME" '.[$path_name].src."connection-id"')
-pathDstConnectionId=$($RLY paths list --json | jq --raw-output --arg path_name "$PATH_NAME" '.[$path_name].dst."connection-id"')
-[ "$pathSrcConnectionId" = "$srcAltConnectionId" ] || { echo 'src path config update failed'; exit 1; }
-[ "$pathDstConnectionId" = "$dstAltConnectionId" ] || { echo 'dst path config update failed'; exit 1; }
+checkResult "$srcAltConnectionId" "$dstAltConnectionId"
 
 # test channel upgrade (non-crossing-hello)
-$RLY tx channel-upgrade init ibc01 ibc0 --ordering ORDER_UNORDERED --connection-hops $srcOrigConnectionId --version ics20-1
-$RLY tx channel-upgrade init ibc01 ibc0 --ordering ORDER_UNORDERED --connection-hops $srcOrigConnectionId --version ics20-1
-$RLY tx channel-upgrade init ibc01 ibc1 --ordering ORDER_UNORDERED --connection-hops $dstOrigConnectionId --version ics20-1
+$RLY tx channel-upgrade init ibc01 ibc0 --ordering UNORDERED --connection-hops $srcOrigConnectionId --version ics20-1
+$RLY tx channel-upgrade init ibc01 ibc0 --ordering UNORDERED --connection-hops $srcOrigConnectionId --version ics20-1
+$RLY tx channel-upgrade init ibc01 ibc1 --ordering UNORDERED --connection-hops $dstOrigConnectionId --version ics20-1
 $RLY tx channel-upgrade execute ibc01
-pathSrcConnectionId=$($RLY paths list --json | jq --raw-output --arg path_name "$PATH_NAME" '.[$path_name].src."connection-id"')
-pathDstConnectionId=$($RLY paths list --json | jq --raw-output --arg path_name "$PATH_NAME" '.[$path_name].dst."connection-id"')
-[ "$pathSrcConnectionId" = "$srcOrigConnectionId" ] || { echo 'src path config update failed'; exit 1; }
-[ "$pathDstConnectionId" = "$dstOrigConnectionId" ] || { echo 'dst path config update failed'; exit 1; }
+checkResult "$srcOrigConnectionId" "$dstOrigConnectionId"
 
 # test channel upgrade cancel
-$RLY tx channel-upgrade init ibc01 ibc0 --ordering ORDER_UNORDERED --connection-hops $srcAltConnectionId --version ics20-1
-$RLY tx channel-upgrade init ibc01 ibc1 --ordering ORDER_UNORDERED --connection-hops $dstAltConnectionId --version ics20-1
+$RLY tx channel-upgrade init ibc01 ibc0 --ordering UNORDERED --connection-hops $srcAltConnectionId --version ics20-1
+$RLY tx channel-upgrade init ibc01 ibc1 --ordering UNORDERED --connection-hops $dstAltConnectionId --version ics20-1
 $RLY tx channel-upgrade cancel ibc01 ibc0  # create situation where ibc0.error_receipt.sequence >= ibc1.channel.upgrade_sequence
 $RLY tx channel-upgrade execute ibc01      # the channel upgrade of ibc1 should be cancelled
-pathSrcConnectionId=$($RLY paths list --json | jq --raw-output --arg path_name "$PATH_NAME" '.[$path_name].src."connection-id"')
-pathDstConnectionId=$($RLY paths list --json | jq --raw-output --arg path_name "$PATH_NAME" '.[$path_name].dst."connection-id"')
-[ "$pathSrcConnectionId" = "$srcOrigConnectionId" ] || { echo 'src path config update failed'; exit 1; }
-[ "$pathDstConnectionId" = "$dstOrigConnectionId" ] || { echo 'dst path config update failed'; exit 1; }
+checkResult "$srcOrigConnectionId" "$dstOrigConnectionId"
+
